# Generated by Django 4.2.6 on 2023-10-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_product_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Service'},
        ),
    ]
