# Generated by Django 4.2.6 on 2023-10-16 06:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Service',
        ),
    ]
