# Generated by Django 4.2.6 on 2023-10-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
